version: '3.8'

networks:
  GLOBAL_NETWORK:
    external: true

services:
  panel:
    build: ./
    container_name: admin-panel
    command: poetry run main.py
    env_file: ./.env
    restart: always
    networks:
      - GLOBAL_NETWORK
